name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build, Tag, and Push Docker image
        uses: docker/build-push-action@v5 
        with:
          context: .
          push: true
          tags: ryanthedev001/ecommercetest:latest 

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master 
        with:
          image-ref: 'ryanthedev001/ecommercetest:latest'
          scan-type: 'image'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
          format: 'table'
