name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ryanthedev001/your-app-name:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: 'ryanthedev001/your-app-name:latest'

      - name: Push Docker image to DockerHub
        run: |
          docker push ryanthedev001/your-app-name:latest
