name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # NOTE: This manual build/push pattern is less robust than using build-push-action, 
      # but we will keep it for now and only apply the immediate fix.

      - name: Build Docker image
        run: |
          # Confirmed image name: ryanthedev001/ecommercetest
          docker build -t ryanthedev001/ecommercetest:latest .

      - name: Scan Docker image with Trivy
        # *** IMMEDIATE FIX: Using '@master' to bypass the tag resolution error ***
        uses: aquasecurity/trivy-action@master 
        with:
          image-ref: 'ryanthedev001/ecommercetest:latest'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH'
          format: 'table'

      - name: Push Docker image to DockerHub
        run: |
          # Confirmed image name: ryanthedev001/ecommercetest
          docker push ryanthedev001/ecommercetest:latest
