name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Tag, and Push Docker image
        # Using build-push-action is the recommended modern approach
        uses: docker/build-push-action@v5 
        with:
          context: .
          push: true
          tags: ryanthedev001/ecommercetest:latest 

      - name: Scan Docker image with Trivy
        # *** FIX FOR THE ERROR ***
        # Replaced the failing '@v0' with a specific, stable version to resolve the "Unable to find version" error.
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          image-ref: 'ryanthedev001/ecommercetest:latest'
          scan-type: 'image'
          format: 'table'
          # Set exit code to 0 to ensure the pipeline continues to the next step (Push)
          exit-code: '0' 
          severity: 'CRITICAL,HIGH'
